import type { PlannedDay, SeasonBlock, TrainingWeek, WorkoutType } from '../../types'
import { postRaceRecovery } from '../../utils/recovery'
import { bridgeEmphasis } from './residuals'

/**
 * Week generation for the season blocks the existing engines don't cover:
 * RECOVER (the shipped R5 formulas turned into actual scheduled days, not
 * prose) and BRIDGE (the residual-aware category-first piece). BUILD and
 * TAPER blocks are generated by the existing engines — a build's plan
 * already contains its taper — so this module deliberately stops there.
 * Wiring blocks into the athlete-facing plan is PR-7.
 */

function shiftIso(iso: string, days: number): string {
  const d = new Date(`${iso}T12:00:00`)
  d.setDate(d.getDate() + days)
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const dd = String(d.getDate()).padStart(2, '0')
  return `${d.getFullYear()}-${m}-${dd}`
}

function dayLabel(iso: string): string {
  const d = new Date(`${iso}T12:00:00`)
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
  return `${days[d.getDay()]} ${d.getMonth() + 1}/${d.getDate()}`
}

function weekDates(startIso: string, endIso: string): string {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  const s = new Date(`${startIso}T12:00:00`)
  const e = new Date(`${endIso}T12:00:00`)
  const sTxt = `${months[s.getMonth()]} ${s.getDate()}`
  return s.getMonth() === e.getMonth()
    ? `${sTxt}–${e.getDate()}`
    : `${sTxt}–${months[e.getMonth()]} ${e.getDate()}`
}

function day(iso: string, type: WorkoutType, workout: string, detail: string, zone = '—', time = '—'): PlannedDay {
  return { day: dayLabel(iso), type, workout, detail, zone, route: '', time }
}

/** Slice a block's date range into 7-day weeks (last week may be short). */
function blockDates(block: SeasonBlock): string[] {
  const out: string[] = []
  let cur = block.startDate
  while (cur <= block.endDate) {
    out.push(cur)
    cur = shiftIso(cur, 1)
  }
  return out
}

function toWeeks(days: PlannedDay[], dates: string[], startWeekNum: number, focus: string): TrainingWeek[] {
  const weeks: TrainingWeek[] = []
  for (let i = 0; i < days.length; i += 7) {
    const chunk = days.slice(i, i + 7)
    const chunkDates = dates.slice(i, i + 7)
    weeks.push({
      num: startWeekNum + weeks.length,
      dates: weekDates(chunkDates[0], chunkDates[chunkDates.length - 1]),
      miles: chunk.filter(d => d.type !== 'rest' && d.type !== 'strength').length * 3, // rough, refined by PR-7 wiring
      focus,
      days: chunk,
    })
  }
  return weeks
}

/**
 * RECOVER block → scheduled days: the R5 rest days first (1/10 mi raced —
 * 1/10 km when high-vert — with the extra-sleep prescription written into
 * each day), then reverse-taper easy movement (volume before speed).
 */
export function recoverWeeks(
  block: SeasonBlock,
  raceMiles: number,
  opts: { highVert?: boolean; startWeekNum?: number } = {},
): TrainingWeek[] {
  const r = postRaceRecovery(raceMiles, { highVert: opts.highVert })
  const dates = blockDates(block)
  const days: PlannedDay[] = dates.map((iso, i) => {
    if (i < r.restDays) {
      return day(iso, 'rest', 'Post-race rest',
        `Full rest day ${i + 1} of ${r.restDays} (1 per ${opts.highVert ? '10 km' : '10 mi'} raced). ` +
        `Sleep +${r.sleepExtraHrPerNight} hr tonight (${r.sleepExtraNights} nights total). Walking is fine; running is not.`)
    }
    const rebuildDay = i - r.restDays
    return rebuildDay % 3 === 2
      ? day(iso, 'rest', 'Rest', 'Reverse taper: recovery still outranks volume.')
      : day(iso, 'run', 'Easy recovery jog',
          `Reverse taper day ${rebuildDay + 1}: ${20 + rebuildDay * 5}–${30 + rebuildDay * 5} min very easy (Z1). ` +
          'Volume comes back before speed — no quality until this block ends.',
          'Z1 · very easy', `${25 + rebuildDay * 5} min`)
  })
  return toWeeks(days, dates, opts.startWeekNum ?? 1,
    'Post-race recovery — absorb the race. Rest first, then easy movement; speed waits.')
}

/**
 * BRIDGE block → residual-aware content:
 *  - toward Hyrox: hold aerobic with 2 runs/wk (one intensity touch —
 *    Hickson '81) while concentrating strength-endurance + glycolytic
 *    circuits (their 15–18 d residuals mean NOW is when they matter);
 *  - toward a running race: hold strength at 1×/wk (Bickel '11) while run
 *    volume rebuilds (Wilson '12: maintenance-dose interference is noise).
 */
export function bridgeWeeks(
  block: SeasonBlock,
  nextIsHyrox: boolean,
  opts: { startWeekNum?: number } = {},
): TrainingWeek[] {
  const emphasis = bridgeEmphasis(nextIsHyrox)
  const dates = blockDates(block)

  // A 7-slot pattern applied cyclically (Mon-anchored patterns aren't
  // needed — the bridge is transition work, not a peaking microcycle).
  const pattern: ((iso: string) => PlannedDay)[] = nextIsHyrox
    ? [
        iso => day(iso, 'run', 'Aerobic hold run', 'Easy Z2 run — the maintenance dose that keeps your base.', 'Z2 · easy', '40 min'),
        iso => day(iso, 'strength', 'Strength-endurance circuit', 'Hyrox-station circuit: wall balls, sled push/pull, lunges, burpee broad jumps — quality over speed.', '—', '45 min'),
        iso => day(iso, 'rest', 'Rest', 'Adaptation happens here.'),
        iso => day(iso, 'run', 'Intensity touch', 'Z2 run finishing with 4–6 × 1 min at threshold — the intensity that preserves aerobic fitness (Hickson 1981).', 'Z2-4', '40 min'),
        iso => day(iso, 'strength', 'Glycolytic capacity', 'Station intervals at race effort: 60–90 s on / 60 s off — the short-residual quality trained closest to race day.', '—', '40 min'),
        iso => day(iso, 'cross', 'Easy cross or walk', 'Optional flush: bike, row, or brisk walk. Skip freely.', 'Z1', '30 min'),
        iso => day(iso, 'rest', 'Rest', 'Adaptation happens here.'),
      ]
    : [
        iso => day(iso, 'run', 'Volume rebuild run', 'Easy Z2 — run volume comes back first.', 'Z2 · easy', '45 min'),
        iso => day(iso, 'rest', 'Rest', 'Adaptation happens here.'),
        iso => day(iso, 'run', 'Easy run + strides', 'Z2 with 4 × 20 s relaxed strides — turnover without cost.', 'Z2', '40 min'),
        iso => day(iso, 'strength', 'Strength maintenance', 'ONE weekly strength dose holds what you built (Bickel 2011). Keep loads honest, volume low.', '—', '35 min'),
        iso => day(iso, 'run', 'Easy run', 'Z2, conversational throughout.', 'Z2 · easy', '45 min'),
        iso => day(iso, 'long', 'Longer easy run', 'The week’s biggest aerobic dose — still easy, still conversational.', 'Z2', '60-75 min'),
        iso => day(iso, 'rest', 'Rest', 'Adaptation happens here.'),
      ]

  const days = dates.map((iso, i) => pattern[i % 7](iso))
  return toWeeks(days, dates, opts.startWeekNum ?? 1,
    `Bridge — ${emphasis.rationale}`)
}
