import type { PlannedDay, SeasonBlock, TrainingWeek, WorkoutType } from '../../types'
import type { CrossTrainingMode } from '../../hooks/useOnboarding'
import { postRaceRecovery } from '../../utils/recovery'
import { CROSS_MODE_LABEL } from '../planGenerator/extraDays'
import { bridgeEmphasis, EV_INTENSITY_PRESERVES, EV_STRENGTH_HOLDS } from './residuals'

/**
 * Week generation for the season blocks the existing engines don't cover:
 * RECOVER (the shipped R5 formulas turned into actual scheduled days, not
 * prose) and BRIDGE (the residual-aware category-first piece). BUILD and
 * TAPER blocks are generated by the existing engines — a build's plan
 * already contains its taper — so this module deliberately stops there.
 * Wiring blocks into the athlete-facing plan is PR-7.
 */

function shiftIso(iso: string, days: number): string {
  const d = new Date(`${iso}T12:00:00`)
  d.setDate(d.getDate() + days)
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const dd = String(d.getDate()).padStart(2, '0')
  return `${d.getFullYear()}-${m}-${dd}`
}

export function dayLabel(iso: string): string {
  const d = new Date(`${iso}T12:00:00`)
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
  return `${days[d.getDay()]} ${d.getMonth() + 1}/${d.getDate()}`
}

export function weekDates(startIso: string, endIso: string): string {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  const s = new Date(`${startIso}T12:00:00`)
  const e = new Date(`${endIso}T12:00:00`)
  const sTxt = `${months[s.getMonth()]} ${s.getDate()}`
  return s.getMonth() === e.getMonth()
    ? `${sTxt}–${e.getDate()}`
    : `${sTxt}–${months[e.getMonth()]} ${e.getDate()}`
}

function day(iso: string, type: WorkoutType, workout: string, detail: string, zone = '—', time = '—'): PlannedDay {
  return { day: dayLabel(iso), type, workout, detail, zone, route: '', time }
}

// Hard iteration guard for the day-by-day walkers. No legitimate block
// spans years — if a corrupt or absurd date range reaches this layer the
// stream must TRUNCATE, never freeze the tab walking millions of days.
const MAX_STREAM_DAYS = 800

/** Slice a block's date range into 7-day weeks (last week may be short). */
function blockDates(block: SeasonBlock): string[] {
  const out: string[] = []
  let cur = block.startDate
  while (cur <= block.endDate && out.length < MAX_STREAM_DAYS) {
    out.push(cur)
    cur = shiftIso(cur, 1)
  }
  return out
}

function toWeeks(days: PlannedDay[], dates: string[], startWeekNum: number, focus: string): TrainingWeek[] {
  const weeks: TrainingWeek[] = []
  for (let i = 0; i < days.length; i += 7) {
    const chunk = days.slice(i, i + 7)
    const chunkDates = dates.slice(i, i + 7)
    weeks.push({
      num: startWeekNum + weeks.length,
      startIso: chunkDates[0],
      dates: weekDates(chunkDates[0], chunkDates[chunkDates.length - 1]),
      miles: chunk.filter(d => d.type !== 'rest' && d.type !== 'strength').length * 3, // rough, refined by PR-7 wiring
      focus,
      days: chunk,
    })
  }
  return weeks
}

/** A dated day plus the (unlabeled) week-focus text it belongs to. The
 *  splice assembler concatenates streams across blocks and re-chunks them
 *  at Monday boundaries so season weeks share the anchor plan's Mon–Sun
 *  convention (the field bug's 3-day and Fri→Thu weeks came from chunking
 *  per-block instead). */
export interface StreamDay {
  iso: string
  day: PlannedDay
  focus: string
}

export const RECOVER_FOCUS =
  'Post-race recovery — absorb the race. Rest first, then easy movement; speed waits.'

/**
 * R3 — athlete scaling for the recover/bridge streams. The stream copy was
 * written for a generic ~25 mi/wk athlete; a 45 mi/wk marathoner's "easy
 * movement" is genuinely more than a 10 mi/wk beginner's, and a masters
 * athlete's return is slower (the same evidence base as the R1 masters
 * policy: recovery cost rises with age — Reaburn & Dascombe 2008).
 */
export interface AthleteScale {
  /** Athlete age — 58+ adds a rest day to the recover block and defers the
   *  bridge's first intensity touch by a week; 70+ adds two rest days and
   *  trims durations a further 15%. */
  age?: number
  /** The weekly volume the previous block actually reached — scales every
   *  stream duration (clamped 0.6–1.6× of the 25 mi/wk baseline copy). */
  priorWeeklyMi?: number
}

const STREAM_BASELINE_WEEKLY_MI = 25

function streamScale(athlete?: AthleteScale): number {
  const vol = athlete?.priorWeeklyMi
  let f = vol && vol > 0 ? Math.min(1.6, Math.max(0.6, vol / STREAM_BASELINE_WEEKLY_MI)) : 1
  if (athlete?.age != null && athlete.age >= 70) f *= 0.85
  return f
}

/** Scale a duration and keep it a human number (nearest 5 min, floor 15). */
function scaleMin(baseMin: number, f: number): number {
  return Math.max(15, Math.round((baseMin * f) / 5) * 5)
}

function extraRestDays(athlete?: AthleteScale): number {
  if (athlete?.age == null) return 0
  if (athlete.age >= 70) return 2
  if (athlete.age >= 58) return 1
  return 0
}

/**
 * RECOVER block → scheduled days: the R5 rest days first (1/10 mi raced —
 * 1/10 km when high-vert — with the extra-sleep prescription written into
 * each day), then reverse-taper easy movement (volume before speed).
 * R3: rest-day count and jog durations scale with age and the volume the
 * athlete actually carried into the race.
 */
export function recoverDayStream(
  block: SeasonBlock,
  raceMiles: number,
  opts: { highVert?: boolean; athlete?: AthleteScale } = {},
): StreamDay[] {
  const r = postRaceRecovery(raceMiles, { highVert: opts.highVert })
  const restDays = r.restDays + extraRestDays(opts.athlete)
  const f = streamScale(opts.athlete)
  const masters = extraRestDays(opts.athlete) > 0
  const dates = blockDates(block)
  return dates.map((iso, i) => {
    if (i < restDays) {
      const mastersNote = i >= r.restDays
        ? ' Extra rest day — recovery cost rises with age, and the race is already banked.'
        : ''
      return {
        iso,
        focus: RECOVER_FOCUS,
        day: day(iso, 'rest', 'Post-race rest',
          `Full rest day ${i + 1} of ${restDays} (1 per ${opts.highVert ? '10 km' : '10 mi'} raced${masters ? ', plus the masters margin' : ''}). ` +
          `Sleep +${r.sleepExtraHrPerNight} hr tonight (${r.sleepExtraNights} nights total). Walking is fine; running is not.` +
          mastersNote),
      }
    }
    const rebuildDay = i - restDays
    return {
      iso,
      focus: RECOVER_FOCUS,
      day: rebuildDay % 3 === 2
        ? day(iso, 'rest', 'Rest', 'Reverse taper: recovery still outranks volume.')
        : day(iso, 'run', 'Easy recovery jog',
            `Reverse taper day ${rebuildDay + 1}: ${scaleMin(20 + rebuildDay * 5, f)}–${scaleMin(30 + rebuildDay * 5, f)} min very easy (Z1). ` +
            'Volume comes back before speed — no quality until this block ends.',
            'Z1 · very easy', `${scaleMin(25 + rebuildDay * 5, f)} min`),
    }
  })
}

export function recoverWeeks(
  block: SeasonBlock,
  raceMiles: number,
  opts: { highVert?: boolean; startWeekNum?: number; athlete?: AthleteScale } = {},
): TrainingWeek[] {
  const stream = recoverDayStream(block, raceMiles, opts)
  return toWeeks(stream.map(s => s.day), stream.map(s => s.iso), opts.startWeekNum ?? 1, RECOVER_FOCUS)
}

/**
 * BRIDGE block → residual-aware content:
 *  - toward Hyrox: hold aerobic with 2 runs/wk (one intensity touch —
 *    Hickson '85) while concentrating strength-endurance + glycolytic
 *    circuits (their 15–18 d residuals mean NOW is when they matter);
 *  - toward a running race: hold strength at 1×/wk (Bickel '11) while run
 *    volume rebuilds (Wilson '12: maintenance-dose interference is noise).
 */
export function bridgeDayStream(
  startIso: string,
  endIso: string,
  nextIsHyrox: boolean,
  patternOffset = 0,
  crossModes?: CrossTrainingMode[],
  athlete?: AthleteScale,
): StreamDay[] {
  const emphasis = bridgeEmphasis(nextIsHyrox)
  const focus = `Bridge — ${emphasis.rationale}`
  // R3 — athlete scaling: run durations follow the volume the athlete
  // actually carried out of the previous block; masters (58+) defer the
  // bridge's first intensity touch (strides / threshold minute) to the
  // second bridge week — intensity is the last thing to come back.
  const f = streamScale(athlete)
  const mastersDefer = athlete?.age != null && athlete.age >= 58
  const min = (base: number) => `${scaleMin(base, f)} min`
  const minRange = (lo: number, hi: number) => `${scaleMin(lo, f)}-${scaleMin(hi, f)} min`
  const dates: string[] = []
  let cur = startIso
  while (cur <= endIso && dates.length < MAX_STREAM_DAYS) {
    dates.push(cur)
    cur = shiftIso(cur, 1)
  }

  // The weekly flush day rotates through the athlete's own cross-training
  // picks (the onboarding promise) — one mode per bridge week; generic
  // copy only when they picked nothing.
  const crossDay = (iso: string, cycle: number): PlannedDay => {
    if (crossModes && crossModes.length > 0) {
      const mode = crossModes[cycle % crossModes.length]
      const label = CROSS_MODE_LABEL[mode]
      return day(iso, 'cross', `Easy cross — ${label}`, `Optional flush: easy ${label.toLowerCase()}. Skip freely.`, 'Z1', '30 min')
    }
    return day(iso, 'cross', 'Easy cross or walk', 'Optional flush: bike, row, or brisk walk. Skip freely.', 'Z1', '30 min')
  }

  // A 7-slot pattern applied cyclically. `patternOffset` lets the splice
  // EXTEND a bridge past its block's end (filling the boundary gap before
  // a Monday-snapped build plan) without repeating the same slot twice.
  const pattern: ((iso: string, cycle: number) => PlannedDay)[] = nextIsHyrox
    ? [
        iso => day(iso, 'run', 'Aerobic hold run', 'Easy Z2 run — the maintenance dose that keeps your base.', 'Z2 · easy', min(40)),
        iso => day(iso, 'strength', 'Strength-endurance circuit', 'Hyrox-station circuit: wall balls, sled push/pull, lunges, burpee broad jumps — quality over speed.', '—', '45 min'),
        iso => day(iso, 'rest', 'Rest', 'Adaptation happens here.'),
        (iso, cycle) => mastersDefer && cycle === 0
          ? day(iso, 'run', 'Aerobic hold run', 'Easy Z2 — intensity waits a week: masters recovery earns its margin before the first threshold touch.', 'Z2 · easy', min(40))
          : day(iso, 'run', 'Intensity touch', `Z2 run finishing with 4–6 × 1 min at threshold — the intensity that preserves aerobic fitness (${EV_INTENSITY_PRESERVES.value}).`, 'Z2-4', min(40)),
        iso => day(iso, 'strength', 'Glycolytic capacity', 'Station intervals at race effort: 60–90 s on / 60 s off — the short-residual quality trained closest to race day.', '—', '40 min'),
        crossDay,
        iso => day(iso, 'rest', 'Rest', 'Adaptation happens here.'),
      ]
    : [
        iso => day(iso, 'run', 'Volume rebuild run', 'Easy Z2 — run volume comes back first.', 'Z2 · easy', min(45)),
        iso => day(iso, 'rest', 'Rest', 'Adaptation happens here.'),
        (iso, cycle) => mastersDefer && cycle === 0
          ? day(iso, 'run', 'Easy run', 'Z2, conversational — strides return next week: masters recovery earns its margin before turnover work.', 'Z2 · easy', min(40))
          : day(iso, 'run', 'Easy run + strides', 'Z2 with 4 × 20 s relaxed strides — turnover without cost.', 'Z2', min(40)),
        iso => day(iso, 'strength', 'Strength maintenance', `ONE weekly strength dose holds what you built (${EV_STRENGTH_HOLDS.value}). Keep loads honest, volume low.`, '—', '35 min'),
        iso => day(iso, 'run', 'Easy run', 'Z2, conversational throughout.', 'Z2 · easy', min(45)),
        iso => day(iso, 'long', 'Longer easy run', 'The week’s biggest aerobic dose — still easy, still conversational.', 'Z2', minRange(60, 75)),
        iso => day(iso, 'rest', 'Rest', 'Adaptation happens here.'),
      ]

  return dates.map((iso, i) => ({
    iso,
    focus,
    day: pattern[(i + patternOffset) % 7](iso, Math.floor((i + patternOffset) / 7)),
  }))
}

export function bridgeWeeks(
  block: SeasonBlock,
  nextIsHyrox: boolean,
  opts: { startWeekNum?: number } = {},
): TrainingWeek[] {
  const stream = bridgeDayStream(block.startDate, block.endDate, nextIsHyrox)
  return toWeeks(stream.map(s => s.day), stream.map(s => s.iso), opts.startWeekNum ?? 1,
    stream[0]?.focus ?? `Bridge — ${bridgeEmphasis(nextIsHyrox).rationale}`)
}
