import { useEffect, useMemo } from 'react'
import type { TrainingPlan, CoachSnapshot } from '../types'
import type { OnboardingConfig } from '../hooks/useOnboarding'
import { useCoachInsight } from '../hooks/useCoachInsight'
import { coachApiAvailable } from '../utils/coachApi'
import { injurySummaryLine } from '../utils/injuryRamp'
import { menopauseSummaryLine } from '../utils/menopause'
import { GOAL_PRESETS } from '../engines/generalFitness/presets'
import { renderMarkdown } from '../utils/markdown'

interface Props {
  plan: TrainingPlan
  config: OnboardingConfig
  athleteId: string
  onContinue: () => void
}

/**
 * Post-onboarding "Letter from your Coach" — a one-time, start-of-season note
 * generated by the coach model from the freshly-built plan + the athlete's
 * free-text race description & goal. Shown once (gated by welcomeLetterSeenAt
 * in App.tsx). Falls back to a short templated note when the coach API isn't
 * configured, so onboarding is never blocked.
 */
export default function CoachLetter({ plan, config, athleteId, onContinue }: Props) {
  // Mirror the onboarding overlay's iOS scroll-reset so the fixed overlay
  // paints in the visible viewport.
  useEffect(() => {
    if (typeof document !== 'undefined') {
      const active = document.activeElement as HTMLElement | null
      if (active && typeof active.blur === 'function') active.blur()
    }
    if (typeof window !== 'undefined') window.scrollTo(0, 0)
  }, [])

  const apiAvailable = coachApiAvailable()

  // Personalize the letter. Lead with the athlete's GOAL — for General Fitness
  // that's the preset (e.g. "Lose Fat"), optionally with their free-text goal;
  // for a race it's their stated race goal. And surface pertinent personal
  // context (injury) so the coach acknowledges it instead of writing generically.
  const goalText =
    config.raceType === 'general'
      ? [GOAL_PRESETS[config.generalGoal ?? 'stay_healthy'].label, config.athleteGoal?.trim()]
          .filter(Boolean)
          .join(' — ')
      : config.athleteGoal
  const injuryLine = injurySummaryLine(config) || undefined
  const menopauseLine = menopauseSummaryLine(config) || undefined

  // The whole season, in the coach's SEASON section: an athlete who listed
  // four races must get a letter about their season, not just race #1.
  const extraRaces = config.additionalRaces ?? []
  const seasonLine = extraRaces.length > 0
    ? [
        `The athlete is training for a ${extraRaces.length + 1}-race season${config.goalMode === 'season' ? ' (they chose season-mode onboarding)' : ''}.`,
        `Race 1 (anchor — this plan): ${plan.race.name}${config.raceDate ? ` on ${config.raceDate}` : ''}${config.athleteGoal?.trim() ? ` — goal: ${config.athleteGoal.trim()}` : ''}.`,
        ...extraRaces.map((r, i) =>
          `Race ${i + 2}: ${r.name} on ${r.date} (${r.format ?? 'race'}, priority ${r.priority})` +
          `${r.description?.trim() ? ` — ${r.description.trim()}` : ''}` +
          `${r.integration === 'layered' ? ' — its specific prep is LAYERED into the current build (1–2 sessions/week now, ramping after race 1)' : ' — its dedicated block starts after the previous race'}.`),
        'The season chains: build → race → recover → bridge → next build; every race gets its own race week.',
      ].join(' ')
    : undefined

  // Lean snapshot: at onboarding end there's no readiness/activity data yet, so
  // hand the coach just the plan + the athlete's own words + their goal/injury.
  // The insight endpoint and context builder are defensive about missing fields.
  const snapshot = useMemo(() => ({
    athleteProfile: plan.athlete,
    race: { ...plan.race, description: config.raceDescription, athleteGoal: goalText },
    zones: plan.zones,
    weeks: plan.weeks,
    currentWeekNum: 1,
    detailLevel: config.detailLevel,
    injuryContext: injuryLine,
    menopauseContext: menopauseLine,
    seasonContext: seasonLine,
  } as unknown as CoachSnapshot), [plan, config, goalText, injuryLine, menopauseLine, seasonLine])

  const { insight, loading, error } = useCoachInsight({
    athleteId,
    surface: 'welcome_letter',
    snapshot,
    enabled: apiAvailable,
  })

  // "Ready" = the coach has responded (or errored), or there's no API to call.
  const ready = !apiAvailable || (!loading && (insight !== null || error !== null))
  const letter = insight?.text?.trim()

  const goalPhrase = goalText?.trim() || config.raceName || 'your goal'
  const injurySentence = injuryLine
    ? ` I see you're ${injuryLine} — we'll ease in and keep an eye on it so it holds up.`
    : ''
  const menopauseSentence = menopauseLine
    ? ` I also see you're ${menopauseLine} — the old "more cardio, lighter weights" advice works against you in midlife, so we'll lean into strength, keep your hard days, and protect your recovery.`
    : ''
  const fallback =
    `Welcome, ${plan.athlete.name || 'athlete'} — your plan is built and ready.\n\n` +
    `It's ${plan.weeks.length} weeks built around ${goalPhrase}.${injurySentence}${menopauseSentence} ` +
    `Trust the process, show up for the easy days as much as the hard ones, and we'll get there together.\n\n` +
    `I'm in the Coach tab whenever you want to talk it through. Let's get to work.`

  return (
    <div className="fixed inset-0 z-50 bg-white dark:bg-slate-900 flex flex-col">
      <div className="flex-1 overflow-y-auto px-5 pt-10 pb-28">
        <p className="text-xs uppercase tracking-wide font-bold text-teal-700">A letter from your coach</p>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white leading-tight mt-1">
          {plan.athlete.name ? `Welcome, ${plan.athlete.name}` : 'Welcome'}
        </h1>

        {!ready && (
          <div className="mt-10 flex flex-col items-center justify-center text-center text-slate-500 dark:text-slate-300">
            <div className="w-8 h-8 border-2 border-teal-500 border-t-transparent rounded-full animate-spin" aria-hidden />
            <p className="mt-4 text-sm">Your coach is writing your start-of-season letter…</p>
          </div>
        )}

        {ready && (
          <div className="mt-5 space-y-3 text-[15px] leading-relaxed text-slate-700 dark:text-slate-200">
            {renderMarkdown(letter || fallback)}
          </div>
        )}
      </div>

      <div className="fixed bottom-0 left-0 right-0 px-5 py-4 bg-white dark:bg-slate-900 border-t border-slate-100 dark:border-slate-700">
        <button
          onClick={onContinue}
          disabled={!ready}
          className={`w-full py-3.5 rounded-xl text-base font-semibold transition ${ready ? 'bg-teal-600 text-white active:bg-teal-700' : 'bg-slate-200 text-slate-400 dark:bg-slate-700 dark:text-slate-500'}`}
        >
          {ready ? 'Start training' : 'Writing…'}
        </button>
      </div>
    </div>
  )
}
